# Makefile - makefile for diskEncryption
#
# Copyright (c) 2016, 2021 Wind River Systems, Inc.
#
# The right to copy, distribute, modify or otherwise make use
# of this software may be licensed only pursuant to the terms
# of an applicable Wind River license agreement.
#
# DESCRIPTION
# Makefile for diskEncryption
#

LIB_BASE_NAME = diskEncryption

OBJS = diskEncryption.o diskEncryptionLib.o diskEncryptionTools.o diskEncryptionAuto.o

DOC_FILES = diskEncryptionTools.c

include $(WIND_KRNL_MK)/rules.library.mk
